/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprint;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nicole
 */
public class CrearSprint extends javax.swing.JPanel {

    /**
     * Creates new form CrearSprint
     */
    public CrearSprint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SprintLabel = new javax.swing.JLabel();
        FechaInicioFormatedField = new javax.swing.JFormattedTextField();
        FechaFinFormatedField = new javax.swing.JFormattedTextField();
        FechaInicioLabel = new javax.swing.JLabel();
        FechaFinLabel = new javax.swing.JLabel();
        NombreSprintLabel = new javax.swing.JLabel();
        NombreSprintTexto = new javax.swing.JTextField();
        CrearBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        SprintLabel.setText("Sprint");

        FechaInicioFormatedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaInicioFormatedFieldActionPerformed(evt);
            }
        });

        FechaFinFormatedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaFinFormatedFieldActionPerformed(evt);
            }
        });

        FechaInicioLabel.setText("Fecha Inicio");

        FechaFinLabel.setText("Fecha Fin");

        NombreSprintLabel.setText("Nombre:");

        CrearBoton.setText("Crear");
        CrearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SprintLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NombreSprintLabel)
                                .addGap(44, 44, 44)
                                .addComponent(NombreSprintTexto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaInicioFormatedField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FechaInicioLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaFinLabel)
                                    .addComponent(FechaFinFormatedField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(CrearBoton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(SprintLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreSprintLabel)
                    .addComponent(NombreSprintTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaInicioLabel)
                    .addComponent(FechaFinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaInicioFormatedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaFinFormatedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CrearBoton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FechaInicioFormatedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaInicioFormatedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaInicioFormatedFieldActionPerformed

    private void CrearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotonActionPerformed
       try {
            ConsultasSprint consulta = new ConsultasSprint();
            consulta.guardarSprint(new Sprint(NombreSprintTexto.getText(),FechaInicioFormatedField.getText(),FechaFinFormatedField.getText()));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearSprint.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearSprint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CrearBotonActionPerformed

    private void FechaFinFormatedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaFinFormatedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaFinFormatedFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBoton;
    private javax.swing.JFormattedTextField FechaFinFormatedField;
    private javax.swing.JLabel FechaFinLabel;
    private javax.swing.JFormattedTextField FechaInicioFormatedField;
    private javax.swing.JLabel FechaInicioLabel;
    private javax.swing.JLabel NombreSprintLabel;
    private javax.swing.JTextField NombreSprintTexto;
    private javax.swing.JLabel SprintLabel;
    // End of variables declaration//GEN-END:variables
}
