/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userstory;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nicole
 */
public class CrearUserStory extends javax.swing.JPanel {

    /**
     * Creates new form CrearUserStory
     */
    public CrearUserStory() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_historia = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        label_desc = new javax.swing.JLabel();
        label_criterio = new javax.swing.JLabel();
        text_titulo = new javax.swing.JTextField();
        text_desc = new javax.swing.JTextField();
        text_criterio = new javax.swing.JTextField();
        label_comp = new javax.swing.JLabel();
        label_priori = new javax.swing.JLabel();
        text_comp = new javax.swing.JTextField();
        text_priori = new javax.swing.JTextField();
        boton_anadir = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        label_historia.setBackground(new java.awt.Color(0, 102, 102));
        label_historia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_historia.setText("Historia de Usuario");

        label_titulo.setText("Titulo:");

        label_desc.setText("Descripcion:");

        label_criterio.setText("Criterios de Aceptacion: ");

        text_titulo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        text_titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_titulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tituloActionPerformed(evt);
            }
        });

        text_desc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_descActionPerformed(evt);
            }
        });

        text_criterio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_criterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_criterioActionPerformed(evt);
            }
        });

        label_comp.setText("Complejidad");

        label_priori.setText("Prioridad");

        text_comp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_compActionPerformed(evt);
            }
        });

        text_priori.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_priori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_prioriActionPerformed(evt);
            }
        });

        boton_anadir.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        boton_anadir.setText("Añadir");
        boton_anadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_anadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_comp))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_priori)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(text_priori, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                    .addComponent(boton_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_titulo)
                                .addComponent(label_criterio)
                                .addComponent(label_desc)
                                .addComponent(text_criterio, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                .addComponent(text_desc)
                                .addComponent(text_titulo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(label_historia)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(label_historia)
                .addGap(18, 18, 18)
                .addComponent(label_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(label_criterio)
                .addGap(18, 18, 18)
                .addComponent(text_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_comp)
                    .addComponent(label_priori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_priori, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tituloActionPerformed

    private void text_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_descActionPerformed

    private void text_criterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_criterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_criterioActionPerformed

    private void text_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_compActionPerformed

    private void text_prioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_prioriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_prioriActionPerformed

    private void boton_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_anadirActionPerformed
        try {
            ConsultasUserStory consulta = new ConsultasUserStory();
            consulta.guardarHistoria(new UserStory(text_titulo.getText(),text_desc.getText(),text_criterio.getText(),Integer.parseInt(text_comp.getText()), Integer.parseInt(text_priori.getText())));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearUserStory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearUserStory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton_anadirActionPerformed
 
        
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_anadir;
    private javax.swing.JLabel label_comp;
    private javax.swing.JLabel label_criterio;
    private javax.swing.JLabel label_desc;
    private javax.swing.JLabel label_historia;
    private javax.swing.JLabel label_priori;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTextField text_comp;
    private javax.swing.JTextField text_criterio;
    private javax.swing.JTextField text_desc;
    private javax.swing.JTextField text_priori;
    private javax.swing.JTextField text_titulo;
    // End of variables declaration//GEN-END:variables


 



}
